config/routes.rb
Rails.application.routes.draw do

  get 'search_stock',to: "stocks#search"

  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [:show, :edit, :update]
  root 'welcome#home'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'my_friends', to: "users#my_friends"

  resources :users, only: [:show, :edit, :update]
  resources :friendships
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ActiveRecord::Base

	has_many :user_stocks
	has_many :users, through: :user_stocks

	def self.find_by_ticker(ticker_symbol)
		where(ticker: ticker_symbol).first
	end

	def self.stock_from_lookup(ticker_symbol)
		looked_up = StockQuote::Stock.quote(ticker_symbol)
		return nil unless looked_up.name
		new_lookup = new(ticker: looked_up.symbol, name: looked_up.name)
		new_lookup.last_price = new_lookup.price
		new_lookup
	end	

	def price
		closing_price = StockQuote::Stock.quote(ticker).close
		return "#{closing_price} (Closing)" if closing_price

		opening_price = StockQuote::Stock.quote(ticker).open
		return "#{opening_price} (Opening)" if opening_price
		'Unavailable'
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships

  mount_uploader :avatar, AvatarUploader

  def full_name
  	return "#{first_name} #{last_name}".strip if (first_name || last_name)
    if !(first_name || last_name)
      return "Anonymous".strip
    end
  	
  end
  def can_add_stock?(ticker_symbol)
  	under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def under_stock_limit?
  	(user_stocks.count < 10)
  end

  def stock_already_added?(ticker_symbol)
  	stock = Stock.find_by_ticker(ticker_symbol)
  	return false unless stock
  	user_stocks.where(stock_id: stock.id).exists?
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?

    param.strip!
    param.downcase!

    (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like?","%#{param}%")
  end 
end

app/models/user_stock.rb
class UserStock < ActiveRecord::Base
	belongs_to :user
	belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	def destroy
		@friendship = current_user.friendships.where(friend_id: params[:id]).first
		@friendship.destroy

		redirect_to my_friends_path
		flash[:danger] = "Friend is auccessfully deleted"
	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
  	if params[:stock]
  		@stock = Stock.find_by_ticker(params[:stock])
  		@stock ||= Stock.stock_from_lookup(params[:stock])
  	end	
  	if @stock
  	   render partial: 'look_up'
  	else
  		render status: :not_found, nothing: true
  	end
  end
end 

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

	before_filter :configure_permitted_parameters

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
		devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)
	end
	
	
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def new
  end

  def create
  	if params[:stock_id].present?
  		@user_stock = UserStock.new(user: current_user, stock_id: params[:stock_id])
  	else
  		stock = Stock.find_by_ticker(params[:stock_ticker])
  		if stock
  			@user_stock = UserStock.new(user: current_user, stock_id: stock)
  		else
  			stock = Stock.stock_from_lookup(params[:stock_ticker])
  			if stock.save
  				@user_stock = UserStock.new(user: current_user, stock: stock)
  			else
  				@user_stock = nil
  				flash[:error] = "Stock is not available"
  			end
  		end
  	end
  	if @user_stock.save
  		flash[:success] = "#{@user_stock.stock.ticker} stock is successfully added"
  		redirect_to my_portfolio_path
  	end
  end

  def destroy
  	@user = current_user
    @user_stock = UserStock.where(:user_id=> @user).where(:stock_id=>params[:id]).first
  	@user_stock.destroy
  	flash[:danger] = "Your stock is successfully deleted"
  	redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  	@user_stocks = current_user.stocks
  	@user = current_user
  end
  def my_friends
  	@my_friends = current_user.friends
  end

  def search
  	@users = User.search(params[:search_params])

  	if @users
  		@users = current_user.except_current_user(@users)
  		render partial: "friends/lookup"
  	else
  		render status: not_found, nothing: true
  	end
  end

  def add_friend
  	@friend = User.find(params[:friend])
  	current_user.friendships.build(friend_id: @friend.id)	
  	if current_user.save
  		redirect_to my_friends_path
  		flash[:success] = "Friend was successfully added"
  	else
  		redirect_to my_friends_path, flash[:danger]="There is an error"
  	end
  end

  def show
  	@user = User.find(params[:id])
  	@user_stocks = @user.stocks
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])
    if @user == current_user
      if @user.update(user_params)
        redirect_to edit_user_path
      else
        render edit_user_path
        flash[:danger] = "Something went wrong"
      end
      else
        redirect_to edit_user_path
        flash[:danger] = "Access Denied"
    end
   
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def avatar_for(user, options = {size: 80})
		size = options[:size]
		if user.avatar?
			image_tag user.avatar.url(:thumb), width: size
		else
			image_tag "avatar.png", width: size
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_lookup.html.erb
<div class="container" id="friend-main-block">
	<div class="row">
		<div class="col-md-7">
			<div>
            	<div class="col-md-12">
            		<h3><strong>Search Friends</strong></h3>
            	</div>
            </div>
			<%=form_tag search_friends_path, remote: true, method: :get, id: 'look-up-friend-form' do %>
			<div class="form-group col-md-7">
				<%= text_field_tag :search_params, params[:search_params], placeholder: 'First name, last name, email', class: 'form-control input-lg', autofocus: true %>
			</div>
			<div class="form-group col-md-5">
				<%=button_tag(type: :submit, class: 'btn btn-lg btn-success look-sub-btn') do %>
					<span id="search-friend-cont"><i class="fa fa-search" aria-hidden="true"></i> Look up friend</span>
					<span id="spin-lookup"><i class="fa fa-cog fa-spin fa-lg" aria-hidden="true"></i> Searching...</span>
				<% end %>
			</div>
			<% end %>
		</div>
	</div> 
	<% if @users %>
		<% if @users.size > 0 %>
			<div class="row" id="friend-lookup-results">
				<div class="col-md-7">
					<div class="well">
						<table class="table">
							<tbody>
								<% @users.each do |user| %>
									<tr>
										<td><strong>Email:</strong> <%= user.email %></td>
										<td><strong>Name:</strong> <%= user.full_name %></td>
										<td><%=link_to 'view profile', user_path(user), class:'btn btn-xs btn-info table-btn' %></td>
										<td>
											<% if current_user.not_friends_with?(user.id) %>
												<%= link_to 'add as friend', add_friend_path(user: current_user, friend: user), method: :post, class: 'btn btn-xs btn-success table-btn' %>
											<% else %>
												<span class="label label-primary">You are friends</span>
											<% end %>
										</td>
									</tr>
								<% end %>	
							</tbody>
						</table>
					</div>
				</div>
			</div>
		<% else %>
			<p> No search criteria matches</p>	
		<% end %>	
	<% end %>
	<div id="friend-lookup-errors"></div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <b><%= link_to '<i class="fa fa-bar-chart fa-2x" aria-hidden="true"></i> Stocks'.html_safe, root_path, class: 'navbar-brand' %></b>
    </div>
    <% if current_user %>
    <ul class="nav navbar-nav">
      
      
      <!-- li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>  -->
    </ul>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      
      <% if current_user %>
        <li><%= link_to 'My Portfolio', my_portfolio_path %></li>
        <li><%= link_to 'My Friends', my_friends_path %></li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>

        <li><%= link_to 'Edit Profile2', edit_user_path(current_user) %></li>
        
        <li>
          <%= link_to current_user.full_name, my_portfolio_path %>
        </li>
        <li class="avatar-nav"><%=link_to avatar_for(current_user, size: 25) %></li>
        <li>

          <%= link_to '<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, method: :delete, class: "btn btn-xs btn-danger" %>
        </li>
      <% else %> 
        <li>
          <%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Up'.html_safe, new_user_registration_path %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path %>
        </li> 
      <% end %>  
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stocktracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
<%= render 'layouts/navbar'%>
	<% flash.each do |name,msg| %>
		<div class="container animated bounceInDown">
			<div class="row">
				<div class="col-md-offset-3 col-md-6">
					<div class="alert alert-dismissible alert-<%= "#{name}" %>">
					  <button type="button" class="close" data-dismiss="alert"><span class="glyphicon glyphicon-remove-circle"></span></button>
					  <b><%= msg %></b>
					</div>
				</div>
			</div>
		</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/stocks/_list.html.erb
<%if @user_stocks.count <= 0 %>
	<h2 align="center">You have not added any stocks yet.</h2>
<% else %>	
	<table class="table table-hover animated bounceInLeft">
		<thead>
			<tr class="stock-list">
				<th>Name</th>
				<th>Symbol</th>
				<th>Current price</th>
				<% if @user.id == current_user.id %>
					<th>Action</th>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<% @user_stocks.each do |user_stock| %>
				<tr class="stock-list-td">
					<td><i class="fa fa-line-chart" aria-hidden="true"></i></i> <%= user_stock.name %></td>
					<td><%= user_stock.ticker %></td>
					<td><%= user_stock.last_price %> </td>
					<% if @user.id == current_user.id %>
						<td>
							<%= link_to 'Delete', user_stock_path(user_stock), method: :delete, data: {confirm: "Are you sure?"},
								class: 'btn btn-xs btn-danger table-btn' %>
						</td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

<br/>
<br/>

app/views/stocks/_look_up.html.erb
<div class="container" id="lookup-main-block">
	<div class="row">
		<div class="col-md-7">
            <div>
            	<div class="col-md-12">
            		<h3 class="animated bounce"><strong>Search stocks</strong></h3>
            	</div>
            </div>
			<%=form_tag search_stock_path, remote: true, method: :get, id: 'look-up-form' do %>

			<div class="form-group col-md-7">

				<%= text_field_tag :stock, params[:stock], placeholder: 'Stock sticker symbol', class: 'form-control input-lg', autofocus: true %>
			</div>
			<div class="form-group col-md-5">
				<%=button_tag(type: :submit, class: 'btn btn-lg btn-success look-sub-btn') do %>
					<span id="search-stock-cont"><i class="fa fa-search" aria-hidden="true"></i> Look up stock</span>
					<span id="spin-lookup"><i class="fa fa-cog fa-spin fa-lg" aria-hidden="true"></i> Searching...</span>
				<% end %>
			</div>
			<% end %>
		</div>
	</div>
	<% if @stock %>
		<div class="row" id="stock-lookup-results">
			<div class="col-md-7">
				<div class="well">

					<strong>Symbol:</strong> <%=@stock.ticker %>
					<strong>Name:</strong> <%=@stock.name %>
					<strong>Price:</strong> <%=@stock.price %>
					
					<% if current_user.can_add_stock?(@stock.ticker) %>
						<%=link_to 'Add to my stocks', user_stocks_path(user: current_user, stock_ticker: @stock.ticker, stock_id: @stock.id ? @stock.id : ''), class:'btn btn-xs btn-success', method: :post %>
					<% else %>
						<span class="label label-danger">
						Stock cannot be added because you have already added
						<% if !current_user.under_stock_limit? && !current_user.stock_already_added?(@stock.ticker) %>
							10 stocks
						<% end %>
							<% if !current_user.under_stock_limit? && current_user.stock_already_added?(@stock.ticker) %>
								10 stocks and maximum limit is 10 stocks.
							<% end %>	
							<% if current_user.stock_already_added?(@stock.ticker) && current_user.under_stock_limit?%>
								this stock
							<% end %>
						</span>
					<% end %>
				</div>
			</div>
		</div>	
	<% end %>
	<div id="lookup-errors"></div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-4 col-md-4">
			<%= form_for(@user, html: {multipart: true}) do |f| %>
				<%= f.label :first_name %>
				<%= f.text_field :first_name %>
				<div>
					<%= f.file_field :avatar %>
				</div>
				<%= f.submit %>
			<% end %>
		</div>
		<div class="col-md-4">
			<%= image_tag @user.avatar.url(:thumb) if @user %>
		</div>
	</div>
</div>

app/views/users/my_friends.html.erb
<%=render 'friends/lookup' %>
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<%if @my_friends.count <= 0 %>
				<h2 align="center">You have not added any friends yet.</h2>
			<% else %>	
				<table class="table table-hover animated slideInUp">
					<thead>
						<tr class="stock-list">
							<th>Name</th>
							<th>Email</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						<% @my_friends.each do |friend| %>
							<tr class="stock-list-td">
								<td><%= friend.full_name %></td>
								<td><%= friend.email %></td>
								<td>
									<%=link_to 'view profile', user_path(friend), class: 'btn btn-xs btn-info table-btn'%>
									<%=link_to 'Unfriend', friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-xs btn-danger table-btn'%>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/look_up' %>

<div class="container">
	<div class="row">
		<div class="col-md-7">
			
				<div class="col-md-12">
					<%= render 'stocks/list' %>
				</div>
			
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title user-detail">
						<b>User Details</b>
					</h2>
				</div>
				<div class="panel-body">
					<%= avatar_for(@user) %>
					<table class="user-detail-table">
						<tr>
							<td><strong><i class="material-icons">account_circle</i> </strong></td>
							<td> <strong> <%= @user.full_name %> </strong></td>
						</tr>
						<tr>
							<td><strong><i class="material-icons">markunread</i> </strong></td>
							<td> <strong> <%= @user.email %> </strong></td>
						</tr>
					</table>
				</div>
			</div>
			<%=image_tag '04.jpg', class: 'img-responsive img-stock'%>
		</div>
		<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title user-detail">
					<b>User Stock List</b>
				</h2>
			</div>
			<div class="panel-body">
				<% if @user.stocks.size > 0 %>
				<%= render 'stocks/list' %>
				<% else %>
				<h3 style="margin:0"><%= @user.first_name %> not tracked any stocks. </h3>
				<% end %>
			</div>
		</div>
			
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 text-center">
			<hr/>
			<%= link_to 'Back', my_friends_path, class: 'btn btn-md btn-danger' %>
		</div>
	</div>	
</div>

app/views/welcome/home.html.erb
<div class="home-page">
	<div class="layer"></div>
</div>
<div class="home-footer text-center">
	<strong>Gambling with cards or dice or stock is all one thing.</strong>
</div>